/* ============================================================
   Write a real page for every chapter, lesson, practice set,
   re-teach and module tab.

     node tools/pages.js            → writes them into the source tree
     node tools/pages.js --check    → writes nothing; exits 1 if stale

   The site does not need a build to run, and still does not: the pages
   this writes are committed alongside everything else, so a copy
   downloaded from GitHub works as it lands. This only has to be run again
   when the curriculum changes — a lesson added, a chapter retitled — and
   `--check` (which the harness runs) says so when it has been forgotten.

   WHERE THINGS GO is not decided here. `assets/js/routes.js` decides it,
   and both this script and every link on the site ask that file, so a link
   cannot point somewhere this script did not write.

   Every file it writes carries MARK in its first lines. Stale pages are
   removed only if they carry it, so nothing written by hand can be deleted
   by a regeneration — however a directory happens to be named.
   ============================================================ */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const MARK = '<!-- generated by tools/pages.js — edit the generator, not this file -->';

const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const up = p => '../'.repeat(p.split('/').filter(Boolean).length);

function stub({ path: p, title, description, theme, css = ['core'], script }) {
  const rel = up(p);
  return `<!DOCTYPE html>
${MARK}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
${css.map(c => `<link rel="stylesheet" href="${rel}assets/css/${c}.css">`).join('\n')}
</head>
<body class="${theme}">
<div id="app"></div>
<script type="module">
${script(rel)}
</script>
</body>
</html>
`;
}

/* ---------------- module tabs ----------------
   The eight original modules each keep several tools behind in-page tab
   buttons. Each tab becomes its own page: the same file, with that tab's
   panel shown and the buttons turned into links to the other tabs' pages.
   The source file itself is left alone — the harness loads its scripts, and
   every panel stays in the DOM so no script finds an element missing. */
const tabSlug = label => label
  .replace(/&amp;/g, '&')
  .replace(/[^\x20-\x7E]/g, ' ')
  .toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

function moduleTabs(file) {
  const src = fs.readFileSync(path.join(ROOT, 'modules', file), 'utf8');
  const tabs = [...src.matchAll(/<button class="tab(?: active)?" onclick="showTab\((\d+),this\)">([\s\S]*?)<\/button>/g)]
    .map(m => ({ i: +m[1], label: m[2].trim(), slug: tabSlug(m[2]) }));
  return { src, tabs };
}

function modulePages() {
  const out = [];
  const files = fs.readdirSync(path.join(ROOT, 'modules')).filter(f => f.endsWith('.html') && f !== 'index.html');
  for (const file of files) {
    const name = file.replace(/\.html$/, '');
    const { src, tabs } = moduleTabs(file);
    if (!tabs.length) continue;
    for (const t of tabs) {
      const p = `modules/${name}/${t.slug}/`;
      let html = src
        .replace('<!DOCTYPE html>', `<!DOCTYPE html>\n${MARK}`)
        .replace(/<title>([\s\S]*?)<\/title>/, (_, x) => `<title>${t.label.replace(/^[^\w&]+/, '').trim()} · ${x}</title>`)
        .replace(/href="\.\.\/index\.html"/g, `href="${up(p)}"`)
        .replace(/<button class="tab(?: active)?" onclick="showTab\((\d+),this\)">([\s\S]*?)<\/button>/g, (_, i, label) => {
          const other = tabs.find(x => x.i === +i);
          const on = +i === t.i;
          return `<a class="tab${on ? ' active' : ''}" href="../${other.slug}/"${on ? ' aria-current="page"' : ''}>${label}</a>`;
        })
        .replace(/<section class="panel(?: active)?" id="panel(\d+)">/g,
          (_, i) => `<section class="panel${+i === t.i ? ' active' : ''}" id="panel${i}">`)
        .replace('</style>', '  a.tab{text-decoration:none;display:inline-block;}\n</style>');
      out.push({ path: p, html });
    }
  }
  return out;
}

/* ---------------- the course ---------------- */
async function coursePages() {
  /* A store with nowhere to persist is what store.js expects in Node; the
     routes and curriculum never touch it, but review.js imports it. */
  globalThis.localStorage ??= { getItem: () => null, setItem() {}, removeItem() {} };
  const R = await import('../assets/js/routes.js');
  const { ACADEMIES } = await import('../assets/js/curriculum.js');
  const { buildIndex } = await import('../assets/js/review.js');
  const { generatorsFor } = await import('../assets/js/generators/index.js');
  const { CONFIG } = await import('../assets/js/config.js');
  const site = CONFIG.identity.name;
  const RUN = ['core', 'lesson', 'widgets'];
  const pages = [];
  const add = pg => pages.push({ path: pg.path, html: stub(pg) });

  for (const a of Object.values(ACADEMIES)) {
    for (const u of a.units) {
      const cp = R.chapterPath(a.id, u.n);
      add({
        path: cp, theme: a.theme,
        title: `${u.title} · ${a.name} · ${site}`,
        description: `Chapter ${u.n}: ${u.sub} ${u.lessons.map(l => l.title).join(', ')}.`,
        script: rel => `import { chapterPage } from '${rel}assets/js/pages.js';\nchapterPage(${JSON.stringify(a.id)}, ${u.n});`,
      });
      if (u.lessons.some(l => l.ready)) {
        add({
          path: R.practicePath(a.id, u.n), theme: a.theme, css: RUN,
          title: `Practice · ${u.title} · ${site}`,
          description: `A practice set drawn from ${u.title} only.`,
          script: rel => `import { practicePage } from '${rel}assets/js/pages.js';\npracticePage(${JSON.stringify(a.id)}, ${u.n});`,
        });
      }
      if (generatorsFor(a.id, u.n).length) {
        add({
          path: R.drillPath(a.id, u.n), theme: a.theme, css: RUN,
          title: `Endless drill · ${u.title} · ${site}`,
          description: `Fresh questions on ${u.title}, built to order — a different paper every time.`,
          script: rel => `import { practicePage } from '${rel}assets/js/pages.js';\npracticePage(${JSON.stringify(a.id)}, ${u.n}, { drill: true });`,
        });
      }
      for (const l of u.lessons) {
        if (!l.ready) continue;
        add({
          path: R.lessonPath(l.id), theme: a.theme, css: RUN,
          title: `${l.title} · ${u.title} · ${site}`,
          description: l.desc,
          script: rel => `import { lessonPage } from '${rel}assets/js/pages.js';\nlessonPage(${JSON.stringify(l.id)});`,
        });
      }
    }
  }

  const index = await buildIndex();
  for (const [id, qs] of index.byConcept) {
    add({
      path: R.reteachPath(id), theme: 'theme-brand', css: RUN,
      title: `Re-teach · ${qs[0].conceptLabel || id} · ${site}`,
      description: `${qs[0].conceptLabel || id}, taught again from the beginning — then fresh questions on it alone.`,
      script: rel => `import { reteachPage } from '${rel}assets/js/pages.js';\nreteachPage(${JSON.stringify(id)});`,
    });
  }
  return pages;
}

/* ---------------- write, prune, check ---------------- */
function generatedOnDisk(dir = ROOT, found = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.') || ['dist', 'tools', 'node_modules', 'assets'].includes(e.name)) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) generatedOnDisk(full, found);
    else if (e.name === 'index.html' && fs.readFileSync(full, 'utf8').slice(0, 300).includes(MARK)) {
      found.push(path.relative(ROOT, dir).split(path.sep).join('/') + '/');
    }
  }
  return found;
}

async function allPages() {
  const pages = [...await coursePages(), ...modulePages()];
  const seen = new Set();
  for (const p of pages) {
    if (seen.has(p.path)) throw new Error(`two pages want ${p.path}`);
    seen.add(p.path);
  }
  return pages;
}

/** What would change. Used by --check and by the harness. */
async function diff() {
  const pages = await allPages();
  const want = new Set(pages.map(p => p.path));
  const stale = pages.filter(p => {
    const f = path.join(ROOT, p.path, 'index.html');
    return !fs.existsSync(f) || fs.readFileSync(f, 'utf8') !== p.html;
  }).map(p => p.path);
  const orphans = generatedOnDisk().filter(p => !want.has(p));
  return { pages, stale, orphans };
}

async function main() {
  const { pages, stale, orphans } = await diff();
  if (process.argv.includes('--check')) {
    if (stale.length || orphans.length) {
      console.log(`Pages out of date: ${stale.length} to write, ${orphans.length} to remove. Run: node tools/pages.js`);
      process.exit(1);
    }
    console.log(`All ${pages.length} generated pages are current.`);
    return;
  }
  for (const p of pages) {
    if (!stale.includes(p.path)) continue;
    fs.mkdirSync(path.join(ROOT, p.path), { recursive: true });
    fs.writeFileSync(path.join(ROOT, p.path, 'index.html'), p.html);
  }
  for (const o of orphans) {
    fs.rmSync(path.join(ROOT, o, 'index.html'));
    /* Take the directory too, but only if that left it empty. */
    let d = path.join(ROOT, o);
    while (d !== ROOT && fs.readdirSync(d).length === 0) { fs.rmdirSync(d); d = path.dirname(d); }
  }
  const count = kind => pages.filter(p => kind(p.path)).length;
  console.log(`${pages.length} pages — ${stale.length} written, ${orphans.length} removed.`);
  console.log(`  chapters ${count(p => /^(reasoning|quants)\/\d+-[^/]+\/$/.test(p))}` +
              ` · lessons ${count(p => /^(reasoning|quants)\/\d+-[^/]+\/[^/]+\/$/.test(p) && !/\/(practice|drill)\/$/.test(p))}` +
              ` · practice ${count(p => /\/practice\/$/.test(p))} · drills ${count(p => /\/drill\/$/.test(p))}` +
              ` · re-teach ${count(p => p.startsWith('reteach/'))} · module tabs ${count(p => p.startsWith('modules/'))}`);
}

if (require.main === module) main().catch(e => { console.error(e); process.exit(1); });

module.exports = { diff, allPages, MARK, moduleTabs, tabSlug };
